' ******************************************************************************
' swxJRNL.swj - journal recorded on 06/01/18 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = _
Application.SldWorks

swApp.ActivateDoc2 "robot_A", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, -0.081631935093278277
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, -0.096474105110237962
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010308350894591534, -0.1187373601356775
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.081631935093278277
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.089053020101758112
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.081631935093278277
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.089053020101758112
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.096474105110237962
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.1038951901187178
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.089053020101758112
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.089053020101758112
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.074210850084798427
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.074210850084798427
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.096474105110237962
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.096474105110237962
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.1038951901187178
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.096474105110237962
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.089053020101758112
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.074210850084798427
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.024052818754046908, -0.081631935093278277
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.020616701789183067, -0.081631935093278277
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.020616701789183067, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.081631935093278277
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.089053020101758112
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.081631935093278277
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.096474105110237962
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.081631935093278277
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.074210850084798427
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.020616701789183067, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.020616701789183067, -0.089053020101758112
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.089053020101758112
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.081631935093278277
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.074210850084798427
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.081631935093278277
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.020616701789183067, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.020616701789183067, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.020616701789183067, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.11131627512719765
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.1187373601356775
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0.1187373601356775
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.074210850084798427
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.074210850084798427
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.020616701789183067, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.014842170016959687, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.014842170016959687, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.014842170016959687, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.014842170016959687, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.014842170016959687, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.014842170016959687, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.014842170016959687, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.014842170016959687, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.014842170016959687, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.014842170016959687, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.044526510050879056, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, -0.037105425042399214, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, -0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.014842170016959687, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.037105425042399214, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.037105425042399214, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.059368680067838749, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.051947595059358899, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.037105425042399214, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.037105425042399214, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.037105425042399214, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.037105425042399214, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.044526510050879056, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.014842170016959687, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.014842170016959687, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, -0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, -0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.030925052683774594, -0.014842170016959687, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.013744467859455376, 0, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.017180584824319219, 0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.017180584824319219, 0.037105425042399214, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.017180584824319219, 0.059368680067838749, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0.044526510050879056, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.044526510050879056, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0.089053020101758112, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.096474105110237962, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.089053020101758112, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.059368680067838749, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.066789765076318591, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.066789765076318591, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.059368680067838749, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.044526510050879056, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.037105425042399214, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.022263255025439528, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.044526510050879056, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010308350894591534, 0.059368680067838749, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0.044526510050879056, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0068722339297276882, 0.029684340033919374, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.014842170016959687, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.014842170016959687, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0034361169648638441, 0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0074210850084798436, 0.15656578615158878, 0.16470892081389366, -0.15258443044473324
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010308350894591534, 0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010308350894591534, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010308350894591534, -0.089053020101758112
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.017180584824319219, -0.11131627512719765
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, -0.1038951901187178
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, -0.074210850084798427
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, -0.074210850084798427
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, -0.074210850084798427
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, -0.081631935093278277
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.081631935093278277
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.020616701789183067, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.027488935718910753, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.020616701789183067, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.024052818754046908, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.024052818754046908, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0.081631935093278277
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0.089053020101758112
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0.081631935093278277
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.074210850084798427
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0068722339297276882, 0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.020616701789183067, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.020616701789183067, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
