' ******************************************************************************
' swxJRNL.swj - journal recorded on 06/01/18 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = _
Application.SldWorks

swApp.ActivateDoc2 "robot_A", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.23747472027135499
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.1558427851780767
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.21521146524591545
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.13357953015263718
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.1187373601356775
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.074210850084798427
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.074210850084798427
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.081631935093278277
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.074210850084798427
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.027488935718910753, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.027488935718910753, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, 0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.066789765076318591
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.1038951901187178
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.14842170016959685
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.074210850084798427
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.027488935718910753, -0.2077903802374356
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.13357953015263718
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.1187373601356775
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.11131627512719765
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.074210850084798427
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.059368680067838749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0068722339297276882, -0.029684340033919374
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017180584824319219, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.020616701789183067, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.022263255025439528
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.020616701789183067, -0.051947595059358899
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.024052818754046908, -0.044526510050879056
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.013744467859455376, -0.037105425042399214
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010308350894591534, -0.014842170016959687
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, -0.0074210850084798436
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0034361169648638441, 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ExitApp
End Sub
